TEXT = {
    'lblLanguage': ['Language', 'زبان'],
    'lblSettingsHeader': ['Settings', 'تنظیمات'],
    'btnUiSettings': [' User Interface',' رابط کاربری'],
    'btnUmSettings': [' User Management',' مدیریت کاربران'],
    'btnHwSettings': [' Hardware   ', ' سخت افزار'],
    'lblUserNumber': ['Enter the user number', 'شماره تلفن کاربر را وارد کنید'],
    'txtNumber': ['Number', 'شماره'],
    'btnStartSession': ['Start Session', 'شروع جلسه'],
    'lblHeaderTutorials': ['Tutorials', 'آموزش ها'],
    'lblVideos': ['Videos', 'فیلم ها'],
    'lblTitle': ['Title', 'عنوان'],
    'lblHeaderFsessions': ['Future Sessions', 'جلسه های آینده'],
    'tbFsessions0': ['Phone Number', 'شماره تلفن'],
    'tbFsessions1': ['Name', 'نام'],
    'tbFsessions2': ['Session Number', 'شماره جلسه'],
    'lblHeaderUm': ['User Management', 'مدیریت کاربران'],
    'usersTable0': ['Phone Number', 'شماره تلفن'],
    'usersTable1': ['Name', 'نام'],
    'usersTable2': ['Sessions', 'تعداد جلسات'],
    'usersTable3': ['Information', 'اطلاعات'],
    'btnSort': ['Sort By Session', 'مرتب سازی تعداد جلسات'],
    'txtSearch': ['Search By Number', 'جستوجو شماره تلفن'],
    'lblNote': ['Note', 'یادداشت'],
    'lblName': ['Name', 'نام'],
    'lblPhoneNumber': ['Phone Number', 'شماره تلفن'],
    'lblNextSession': ['Next Session', 'جلسه بعدی'],
    'lblHeaderUserInfo': ['User Information', 'اطلاعات کاربر'],
    'btnNextSession': ['Next Session', 'جلسه بعد'],
    'btnSaveHw': ['Save', 'ذخیره'],
    'btnSaveInfo': ['Save', 'ذخیره'],
    'btnDeleteUser': ['Delete User', 'حذف کاربر'],
    'userInfoTable0': ['Date', 'تاریخ'],
    'userInfoTable1': ['Face', 'صورت'],
    'userInfoTable2': ['Armpit', 'زیربغل'],
    'userInfoTable3': ['Arm', 'بازو'],
    'userInfoTable4': ['Body', 'بدن'],
    'userInfoTable5': ['Bikini', 'بیکینی'],
    'userInfoTable6': ['Leg', 'پا'],
    'lblMFace': ['Face', 'صورت'],
    'lblMArmpit': ['Armpit', 'زیربغل'],
    'lblMArm': ['Arm', 'بازو'],
    'lblMBody': ['Body', 'بدن'],
    'lblMBikini': ['Bikini', 'بیکینی'],
    'lblMLeg': ['Leg', 'پا'],
    'lblFFace': ['Face', 'صورت'],
    'lblFArmpit': ['Armpit', 'زیربغل'],
    'lblFArm': ['Arm', 'بازو'],
    'lblFBody': ['Body', 'بدن'],
    'lblFBikini': ['Bikini', 'بیکینی'],    
    'lblFLeg': ['Leg', 'پا'],        
    'userInfoTable7': ['Total', 'جمع کل'],
    'notSet': ['Not Set', 'تنظیم نشده'],
    'today': ['Today', 'امروز'],
    '1dayPassed': ['One Day Passed', 'یک روز گذشت'],
    '1dayleft': ['One Day left', 'یک روز باقی مانده'],
    'nDayPassed': ['Days passed', 'روز گذشت'],
    'nDayLeft': ['Days left', 'روز باقی مانده'],
    'passedDate': ['A past date cannot be set.', 'تاریخ گذشته قابل تنظیم نیست.'],
    'invalidDateF':['Invalid date format.', 'قالب تاریخ نامعتبر است.'],
    'emptyNumber': ['Please fill in the number.', 'لطفا شماره را وارد کنید.'],
    'userBeenDeleted': ['User has been deleted!', 'کاربر حذف شده است!'],
    'alreadyExists': ['A user with this phone number already exists!', 'کاربری با این شماره تلفن از قبل وجود دارد!'],
    'userUpdated': ["User's info Updated.", 'اطلاعات کاربر به روز شد.'],
    'sssionNotOver': ['The previous session is not over yet.', 'جلسه قبلی هنوز تموم نشده است.'],
    'alreadyExistsSub': ['User already exists!', 'کاربر از قبل وجود دارد.'],
    'lblDate': ['Date', 'تاریخ'],
    'lblDays': ['Days', 'روز'],
    'lblDaysAfter': ['Next Session After', 'جلسه بعدی، بعد از'],
    'btnCancelNS': ['Cancel', 'لغو'],
    'btnOkNS': ['OK', 'ثبت'],
    'lblHeaderNextSession': ['Next Session', 'جلسه بعدی'],
    'lblHeaderNewUser': ['New User', 'کاربر جدید'],
    'lblEnterUserInfo': ['Enter the user information', 'مشخصات کاربر را وارد کنید'],
    'txtNumberSubmit': ['Number', 'شماره'],
    'txtNameSubmit': ['Name', 'نام'],
    'btnSubmit': ['Submit', 'ثبت'],
    'btnEndSession': ['End Session', 'پایان جلسه'],
    'btnFemale': ['Female', ' زن '],
    'btnMale': [' Male    ',' مرد '],
    'lblEnergy': ['Energy   →', '→   انرژی'],
    'lblFrequency': ['Frequency   →', '→   فرکانس'],
    'lblPulseWidth': ['Pulse Width   →', '→   پهنای پالس'],
    'lblCounter': ['Counter   →', '→   شمارنده'],
    'face': ['Face', 'صورت'],
    'armpit': ['Armpit', 'زیربغل'],
    'arm': ['Arm', 'بازو'],
    'body': ['Body', 'بدن'],
    'bikini': ['Bikini', 'بیکینی'],
    'leg': ['Leg', 'پا'],
    'btnReady': ['Ready', 'آماده'],
    'btnStandby': ['Standby', 'غیر فعال'],
    'total': ['Total','جمع کل'], 
    'firstTime': ['First Time', 'اولین جلسه'],
    'lblSerialNumber': ['Serial Number', 'شماره سریال'],
    'lblTotalShotCounter': ['Total Shot Counter', 'مجموع شات ها'],
    'lblLaserDiodeEnergy': ['Laser Diode Energy', 'سطح انرژی لیزر'],
    'lblLaserBarType': ['Laser Bar Type', 'نوع لیزر بار'],
    'lblLaserWavelength': ['Laser Wavelength', 'طول موج لیزر'],
    'lblDriverVersion': ['Driver Version', 'ورژن درایور'],
    'lblMainControlVersion': ['Main Control Version', 'ورژن برد کنترل'],
    'lblFirmwareVersion': ['Firmware Version', 'ورژن فریموور'],
    'lblProductionDate': ['Production Date', 'تاریخ تولید'],
    'lblOsSpecification': ['OS Specification', 'سیستم عامل'],
    'lblMonitor': ['Monitor', 'نمایشگر'],
    'lblRpiVersion': ['RPi Version', 'ورژن رزبری پای'],
    'lblGuiVersion':['GUI Version', 'ورژن رابط کاربری'],
    'btnEnterHw': ['Enter', 'ورود'],
    'txtHwPass': ['Password', 'رمز عبور'],
    'saveHw': ['Updated.', 'بروزرسانی شد.'],
    'systemTimeStatus': ['Could not set system time.', 'زمان سیستم تنظیم نشد.'],
    'btnResetCounter': ['Reset Counter', 'ریست شمارنده'],
    'lblProducion': ['Production', 'تولید'],
    'lblLaser': ['Laser', 'لیزر'],
    'lblDriver': ['Driver', 'درایور'],
    'lblEmbedded': ['Embedded System', 'سیستم تعبیه شده'],
    'lblSkinGrade': ['Skin Grade', 'گرید پوستی'],
    'lblCooling': ['Cooling', 'سرمایش'],
    'btnHwinfo': ['System Info', 'اطلاعات سیستم'],
    'btnSystemLock': ['Lock && Time', 'قفل و زمان'],
    'lblDefineLock': ['Define a Lock', 'تعریف یک قفل'],
    'lblSysClock': ['System Clock', 'ساعت سیستم'],
    'lblSysDate': ['System Date', 'تاریخ سیستم'],
    'lblEditClock': ['Edit Clock', 'تنظیم ساعت'],
    'lblEditDate': ['Edit Date', 'تنظیم تاریخ'],
    'tableLock0': ['Date', 'تاریخ'],
    'tableLock1': ['Status' ,'وضعیت'],
    'tableLock2': ['Paid', 'پرداخت شده'],
    'tableLock3': ['Remove', 'پاک کردن'],
    'anyLockBefor': ['The lock date must be earlier than the last one.', 'تاریخ قفل باید از تاریخ اخرین قفل جلوتر باشد.'],
    'maxLock': ['A maximum of 3 locks can be defined.', 'حداکثر 3 قفل می تواند تعریف شود.'],
    'yes': ['Yes', 'بله'],
    'no': ['No', 'خیر'],
    'lblCurrentUser': ['Name', 'نام'],
    'lblCurrentSnumber': ['S Number', 'شماره جلسه'],
    'tempError': ['Temperature Sensor Error', 'خطای سنسور دما'],
    'waterflowError': ['Water Flow Sensor Error', 'خطای سنسور جریان آب'],
    'waterLevelError': ['Water Level Sensor Error', 'خطای سنسور سطح آب'],
    'interLockError': ['Inter Lock Swith Error', 'خطای سوئیچ قفل داخلی'],
    'overHeatError': ['OverHeat Error', 'خطای گرمای بیش از حد'],
    'physicalDamage': ['Physical Damage', 'آسیب فیزیکی'],
    'lblOwnerInfo': ['Owner Information', 'اطلاعات مالک'],
    'btnShowSplash': ['Splash Page', 'صفحه اسپلش'],
    'btnUpdateFirmware': ['Update Firmware', 'بروزرسانی فریموور ']
}