TEXT = {
    'lblLanguage': ['Language', 'زبان'],
    'lblSettingsHeader': ['Settings', 'تنظیمات'],
    'btnUiSettings': [' User Interface',' رابط کاربری'],
    'btnUmSettings': [' User Management',' مدیریت کاربران'],
    'btnHwSettings': [' Hardware   ', ' سخت افزار'],
    'lblUserNumber': ['Enter the user number', 'شماره تلفن کاربر را وارد کنید'],
    'txtNumber': ['Number', 'شماره'],
    'btnLogin': ['Start Session', 'شروع جلسه'],
    'lblHeaderTutorials': ['Tutorials', 'آموزش ها'],
    'lblVideos': ['Videos', 'فیلم ها'],
    'lblTitle': ['Title', 'عنوان'],
    'lblHeaderFsessions': ['Future Sessions', 'جلسه های آینده'],
    'tbFsessions0': ['Phone Number', 'شماره تلفن'],
    'tbFsessions1': ['Last Session', 'جلسه قبلی'],
    'tbFsessions2': ['Session Number', 'شماره جلسه'],
    'lblHeaderUm': ['User Management', 'مدیریت کاربران'],
    'usersTable0': ['Phone Number', 'شماره تلفن'],
    'usersTable1': ['Name', 'نام'],
    'usersTable2': ['Sessions', 'تعداد جلسات'],
    'usersTable3': ['Information', 'اطلاعات'],
    'btnSort': ['Sort By Session', 'مرتب سازی تعداد جلسات'],
    'txtSearch': ['Search By Number', 'جستوجو شماره تلفن'],
    'lblNote': ['Note', 'یادداشت'],
    'lblName': ['Name', 'نام'],
    'lblPhoneNumber': ['Phone Number', 'شماره تلفن'],
    'lblNextSession': ['Next Session', 'جلسه بعدی'],
    'lblHeaderUserInfo': ['User Information', 'اطلاعات کاربر'],
    'btnNextSession': ['Next Session', 'جلسه بعد'],
    'btnSaveInfo': ['Save', 'ذخیره'],
    'btnDeleteUser': ['Delete User', 'حذف کاربر'],
    'userInfoTable0': ['Date', 'تاریخ'],
    'userInfoTable1': ['Face', 'صورت'],
    'userInfoTable2': ['Armpit', 'زیربغل'],
    'userInfoTable3': ['Arm', 'بازو'],
    'userInfoTable4': ['Body', 'بدن'],
    'userInfoTable5': ['Bikini', 'بیکینی'],
    'userInfoTable6': ['Leg', 'پا'],
    'userInfoTable7': ['Total', 'جمع کل'],
    'notSet': ['Not Set', 'تنظیم نشده'],
    'today': ['Today', 'امروز'],
    '1dayPassed': ['One Day Passed', 'یک روز گذشت'],
    '1dayleft': ['One Day left', 'یک روز باقی مانده'],
    'nDayPassed': ['Days passed', 'روز گذشت'],
    'nDayLeft': ['Days left', 'روز باقی مانده'],
    'passedDate': ['A past date cannot be set.', 'تاریخ گذشته قابل تنظیم نیست.'],
    'invalidDateF':['Invalid date format.', 'قالب تاریخ نامعتبر است.'],
    'emptyNumber': ['Please fill in the number.', 'لطفا شماره را وارد کنید.'],
    'userBeenDeleted': ['User has been deleted!', 'کاربر حذف شده است!'],
    'alreadyExists': ['A user with this phone number already exists!', 'کاربری با این شماره تلفن از قبل وجود دارد!'],
    'userUpdated': ["User's info Updated.", 'اطلاعات کاربر به روز شد.'],
    'sssionNotOver': ['The previous session is not over yet. ', ' .جلسه قبلی هنوز تموم نشده است'],
    'alreadyExistsSub': ['User already exists!', 'کاربر از قبل وجود دارد.'],
    'lblDate': ['Date', 'تاریخ'],
    'lblDays': ['Days', 'روز'],
    'lblDaysAfter': ['Next Session After', 'جلسه بعدی، بعد از'],
    'btnCancelNS': ['Cancel', 'لغو'],
    'btnOkNS': ['OK', 'ثبت'],
    'lblHeaderNextSession': ['Next Session', 'جلسه بعدی'],
    'lblHeaderNewUser': ['New User', 'کاربر جدید'],
    'lblEnterUserInfo': ['Enter the user information', 'مشخصات کاربر را وارد کنید'],
    'txtNumberSubmit': ['Number', 'شماره'],
    'txtNameSubmit': ['Name', 'نام'],
    'btnSubmit': ['Submit', 'ثبت'],
    'btnEndSession': ['End Session', 'پایان جلسه'],
    'btnFemale': ['Female', ' زن '],
    'btnMale': [' Male    ',' مرد '],
    'lblEnergy': ['Energy', 'انرژی'],
    'lblFrequency': ['Frequency', 'فرکانس'],
    'lblPulseWidth': ['Pulse Width', 'پهنای پالس'],
    'lblCounter': ['Counter', 'شمارنده'],
    'face': ['Face', 'صورت'],
    'armpit': ['Armpit', 'زیربغل'],
    'arm': ['Arm', 'بازو'],
    'body': ['Body', 'بدن'],
    'bikini': ['Bikini', 'بیکینی'],
    'leg': ['Leg', 'پا'],
    'lblReady': ['Ready', 'آماده'],
    'lblStandby': ['Standby', 'استندبای'],
    'total': ['Total','جمع کل'], 
    'firstTime': ['First Time', 'اولین جلسه'],
}